- hosts: all
  tasks:
    - name: create common directories
      file:
        path: "{{ item }}"
        state: directory
      loop: '{{ node_directories_to_create }}'

    - name: install neccessary packages
      become: True
      yum:
        name: "{{ item }}"
        state: present
      loop: '{{ packages_to_install }}'

    - name: create a welcome message
      become: True
      template:
        src: ~/ansible-task/templates/welcome_message.j2
        dest: /etc/profile.d/welcome_message.sh
        owner: root
        group: root
        mode: '0644'

- hosts: apps
  tasks:
    - name: create configuration for apps
      template:
        src: ~/ansible-task/templates/config.properties.j2
        dest: /home/ec2-user/config/config.properties
        owner: ec2-user
        group: ec2-user
        mode: '0644'